# Пример 03. Группа Гейзенберга и её коммутатор

## Тема

**Раздел книги:** Линейная алгебра.  
**Математическая тема:** матричные группы, группа Гейзенберга, некоммутативность, коммутатор; связь с SLAM-алгоритмами для автономных роботов.

## Условие

Рассматривается группа верхних унитреугольных матриц вида

$$\begin{pmatrix}1 & x & z \\ 0 & 1 & y \\ 0 & 0 & 1\end{pmatrix},$$

параметризованная числами $x, y, z\in\mathbb{R}$. Требуется вычислить произведения $AB$ и $BA$ для конкретных матриц, проверить коммутативность и изучить коммутатор $[A,B] = AB - BA$.

## Математическая идея

Группа Гейзенберга $H_3(\mathbb{R})$ — это множество матриц указанного вида с операцией матричного умножения. Прямое вычисление показывает, что

$$\begin{pmatrix}1 & x_1 & z_1 \\ 0 & 1 & y_1 \\ 0 & 0 & 1\end{pmatrix}\begin{pmatrix}1 & x_2 & z_2 \\ 0 & 1 & y_2 \\ 0 & 0 & 1\end{pmatrix} = \begin{pmatrix}1 & x_1+x_2 & z_1+z_2+x_1 y_2 \\ 0 & 1 & y_1+y_2 \\ 0 & 0 & 1\end{pmatrix}.$$

Ключевое наблюдение: правый верхний элемент произведения содержит слагаемое $x_1 y_2$, которого нет при умножении в обратном порядке. Поэтому группа **некоммутативна**, а коммутатор

$$[A,B] = AB - BA$$

имеет единственный ненулевой элемент в позиции $(1,3)$, равный $x_1 y_2 - x_2 y_1$.

## Решение

1. Строятся две матрицы $A$ и $B$ с заданными параметрами.
2. Вычисляются произведения $AB$ и $BA$.
3. Проверяется, что $AB \ne BA$, и находится их разница в верхнем правом углу.
4. Во второй части берутся матрицы с параметрами $(1,0,0)$ и $(0,1,0)$, что делает коммутатор особенно наглядным.

## Реализация на Python

Функция `matrix_in_G(x, y, z)` собирает матрицу из группы Гейзенберга. Произведение `A @ B` использует оператор матричного умножения NumPy. Функция `np.allclose(AB, BA)` проверяет равенство матриц с учётом численной погрешности. Разница `AB[0, 2] - BA[0, 2]` выделяет ненулевую компоненту коммутатора.


In [1]:
import numpy as np

def matrix_in_G(x, y, z):
    return np.array([[1, x, z],
                    [0, 1, y],
                    [0, 0, 1]])

A = matrix_in_G(1, 2, 3)
B = matrix_in_G(4, 5, 6)
AB = A @ B
print("AB =\n", AB)

AB =
 [[ 1  5 14]
 [ 0  1  7]
 [ 0  0  1]]


In [3]:
BA = B @ A
print("BA =\n", BA)
print("\nAB == BA?", np.allclose(AB, BA))

BA =
 [[ 1  5 17]
 [ 0  1  7]
 [ 0  0  1]]

AB == BA? False


## Дополнительный пример

**Идея.** В SLAM-алгоритмах (Simultaneous Localization and Mapping) положение робота в пространстве описывается движениями по специальной евклидовой группе $SE(3)$, которая обобщает группу Гейзенберга. Некоммутативность означает, что порядок поворотов и сдвигов влияет на итоговое положение: повернуть, а потом сдвинуть — не то же самое, что сдвинуть, а потом повернуть. Понимание коммутатора помогает корректно объединять ошибки измерений.

**Что демонстрирует код.** Берутся две матрицы с минимальными параметрами $(1,0,0)$ и $(0,1,0)$, и явно показывается, что их коммутатор $[A,B]$ имеет единственную ненулевую компоненту — точно ту, что отвечает за «взаимное влияние» двух перемещений.


In [4]:
def heisenberg_matrix(x, y, z=0):
    return np.array([[1, x, z],
                    [0, 1, y],
                    [0, 0, 1]])

A = heisenberg_matrix(1, 0)
B = heisenberg_matrix(0, 1)
AB = A @ B
print("AB =\n", AB)
BA = B @ A
print("\nBA =\n", BA)
print("\nРазница в z-координате:", AB[0, 2] - BA[0, 2])

AB =
 [[1 1 1]
 [0 1 1]
 [0 0 1]]

BA =
 [[1 1 0]
 [0 1 1]
 [0 0 1]]

Разница в z-координате: 1


## Проверка результата

Проверка выполняется сравнением матриц `AB` и `BA` через `np.allclose`. Для конкретных параметров демонстрируется, что `AB[0,2] - BA[0,2]` равно $x_A y_B - x_B y_A$, что совпадает с теоретическим значением коммутатора.

## Вывод

Группа Гейзенберга — это простейший пример некоммутативной матричной группы. Её структура лежит в основе более сложных групп преобразований, используемых в робототехнике и компьютерном зрении. Понимание коммутатора помогает правильно составлять уравнения ошибок и оценивать ковариацию в SLAM-алгоритмах.
